# Generated by Django 3.2.8 on 2023-02-07 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCashAmount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dateTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed')], default='Confirmed', max_length=10)),
                ('totalCarnes', models.DecimalField(decimal_places=0, max_digits=10)),
                ('totalGetnet', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=5)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('type', models.CharField(choices=[('Bill', 'Bill'), ('Coin', 'Coin')], max_length=4)),
                ('displayOrder', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Drawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('New', 'Nuevo'), ('Open', 'Abierto'), ('Closed', 'Cerrado')], default='New', max_length=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ClosingBalanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.DecimalField(decimal_places=0, max_digits=7)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.closingbalance')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.denomination')),
            ],
        ),
        migrations.AddField(
            model_name='closingbalance',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.drawer'),
        ),
    ]
