# Generated by Django 3.2.8 on 2023-01-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20230130_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Closed', 'Closed')], default='New', max_length=10),
        ),
    ]
